### PR TITLE
Update to Vue3: Using new plugin install, teleport, removing portal

### PR DESCRIPTION
**Pull request by marcus-herrmann**
Hi,

this PR makes vue-a11y-dialog compatible with Vue 3 by:
- Using its new syntax for installing plugins
- Using Vue3's native teleport instead of vue-portal (which hence won't get an update for Vue3)
- Adapting the tests to my knowledge, namely
  - stubbing teleport
  - Removing `wrapper.vm.$destroy` call in the test, since this method call got removed in Vue3 https://v3.vuejs.org/guide/migration/introduction.html#removed-apis

Also updates to ally-dialog@5.4.1

### CODE REVIEW

**Comment by morkro** [comment]
Ha! I was planning to work on this, but you beat me to it :D Thanks for the work @marcus-herrmann, I'll merge your work this weekend and prepare a new release (as well as keeping the the version for Vue 2 alive).

**Comment by morkro** [comment]
Thanks @marcus-herrmann, I've merged your work. I am still holding on to publishing, as I am running into a couple of issues with my local testing setup. Were you able to run `npm run test` locally?

**Comment by marcus-herrmann** [comment]
@morkro Yep:

screenshot of successfully running npm run test

**Comment by morkro** [comment]
Do you have anything installed globally? I am getting a long list of errors unfortunately.
 
Screenshot 2020-11-02 at 09 05 05

**Comment by kleinfreund** [comment]
I checked out the repository yesterday and ran all scripts defined in the package.json successfully. No errors or unexpected warnings were shown. I’m running Ubuntu.

**Comment by marcus-herrmann** [comment]
> Do you have anything installed globally?

**Comment by marcus-herrmann** [comment]
@morkro Can I help in any way with the broken tests or is this somehow connected to your machine?

**Comment by morkro** [comment]
I still don't know if this is just a local issue and have made no progress so far. I was able to get different kinds of error messages, but that's about it. I did not have more time to spend on it since then, but will look into it again the coming days.

**Comment by morkro** [comment]
For reference, this is the same issue I have https://github.com/vuejs/vue-test-utils-next/issues/246

**Comment by kleinfreund** [comment]
Is there a chance to get this change released?

**Comment by morkro** [comment]
Hey @marcus-herrmann and @kleinfreund, I have published `1.0.0` this morning. Sorry about the long delay, it's been a difficult time. If you encounter any issues with the new version please reach out :)

**Pull request merged**
